// Generated by CoffeeScript 1.6.3
var Game,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Phaser.Game.prototype.constructor = Phaser.Game;

module.exports = Game = (function(_super) {
  __extends(Game, _super);

  function Game() {
    Game.__super__.constructor.call(this, 800, 600, Phaser.AUTO, 'content', null);
    this.state.add('Boot', require("./Boot"), false);
    this.state.add('Preloader', require("./Preloader"), false);
    this.state.add('MainMenu', require("./MainMenu"), false);
    this.state.add('Level1', require("./Level1"), false);
    this.state.start('Boot');
  }

  return Game;

})(Phaser.Game);
