// Generated by CoffeeScript 1.6.3
var MainMenu, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Phaser.State.prototype.constructor = Phaser.State;

module.exports = MainMenu = (function(_super) {
  __extends(MainMenu, _super);

  function MainMenu() {
    _ref = MainMenu.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  MainMenu.prototype.background = Phaser.Sprite;

  MainMenu.prototype.logo = Phaser.Sprite;

  MainMenu.prototype.create = function() {
    this.background = this.add.sprite(0, 0, 'titlepage');
    this.background.alpha = 0;
    this.logo = this.add.sprite(this.world.centerX, -300, 'logo');
    this.logo.anchor.setTo(0.5, 0.5);
    this.add.tween(this.background).to({
      alpha: 1
    }, 2000, Phaser.Easing.Bounce.InOut, true);
    this.add.tween(this.logo).to({
      y: 220
    }, 2000, Phaser.Easing.Elastic.Out, true, 2000);
    return this.input.onDown.addOnce(this.fadeOut, this);
  };

  MainMenu.prototype.fadeOut = function() {
    var tween;
    this.add.tween(this.background).to({
      alpha: 0
    }, 2000, Phaser.Easing.Linear.None, true);
    tween = this.add.tween(this.logo).to({
      y: 800
    }, 2000, Phaser.Easing.Linear.None, true);
    return tween.onComplete.add(this.startGame, this);
  };

  MainMenu.prototype.startGame = function() {
    return this.game.state.start('Level1', true, false);
  };

  return MainMenu;

})(Phaser.State);
