// Generated by CoffeeScript 1.6.3
var Preloader, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Phaser.State.prototype.constructor = Phaser.State;

module.exports = Preloader = (function(_super) {
  __extends(Preloader, _super);

  function Preloader() {
    _ref = Preloader.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Preloader.prototype.preloadBar = Phaser.Sprite;

  Preloader.prototype.preload = function() {
    this.preloadBar = this.add.sprite(200, 250, 'preloadBar');
    this.load.setPreloadSprite(this.preloadBar);
    this.load.image('titlepage', 'assets/titlepage.jpg');
    this.load.image('logo', 'assets/logo.png');
    this.load.audio('music', 'assets/title.mp3', true);
    this.load.spritesheet('simon', 'assets/simon.png', 58, 96, 5);
    return this.load.image('level1', 'assets/level1.png');
  };

  Preloader.prototype.create = function() {
    var tween;
    tween = this.add.tween(this.preloadBar).to({
      alpha: 0
    }, 1000, Phaser.Easing.Linear.None, true);
    return tween.onComplete.add(this.startMainMenu, this);
  };

  Preloader.prototype.startMainMenu = function() {
    return this.game.state.start('MainMenu', true, false);
  };

  return Preloader;

})(Phaser.State);
